version: "3.9"
services:
  backend:
    build: ./backend/docker
    ports:
      - "5000:5000"
  ai-engine:
    build: ./ai-engine
    ports:
      - "6000:6000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: afyalink
      POSTGRES_PASSWORD: afyalink
      POSTGRES_DB: afyalink
volumes:
  dbdata:
